### ISSUE TITLE
Problem on older tmux (1.8)

### ISSUE THREAD

**Issue by eddiec** [peikk0/tmux-cssh#5]
Hi,
Set this up on my Ubuntu laptop with tmux v3 and it worked great.
Tried same thing on CentOS system with tmux 1.8 and it failed.

Tracked it down to line 92:
  tmux split-window -t "${tmux_session}" -t ${tmux_window} -d "ssh ${ssh_options} ${host}"

There are 2 "-t" options and the second (tmux-window) is empty causing it to swallow the "-d".
I don't know tmux at all but in my case I simply removed the "-t ${tmux_window}" and it seems to be working.
My laptop also reports tmux-window as empty but maybe the parser is a bit more lenient in newer versions?

Cheers

**Comment by peikk0** [comment]
This is fixed in afe4163a9bee986f53ee314d8af27d3399689466.
